### ISSUE TITLE
Mail Plugin Not Compatible with v12.4

### ISSUE THREAD

**Issue by masbog** [pixelomer/AltDeploy#15] opened 2020-01-08 05:33 UTC
Hi, i still use MacOS Mojave (10.14.6) and Mail.app version 12.4, while enable plugin for it, i got error:
![image](https://user-images.githubusercontent.com/663374/71952865-e0c49080-3212-11ea-8789-8ff1941956d8.png)

Thanks... i hope the mail plug-in will support on my MacOS version 🙏

**Comment by gatekeeper1122** [comment] 2020-01-09 08:21
can we get this working for mail app v11.5? i use a MacOS High Sierra v10.13.6

![image](https://user-images.githubusercontent.com/16184353/72050419-51ed5d80-327e-11ea-99f0-99266ca9c3cf.png)

**Comment by pixelomer** [comment] 2020-01-09 18:07
Duplicate of #1.

**Closed as completed by pixelomer** 2020-01-09 18:07 UTC
